language: rust
rust:
    - stable
    - beta
    - nightly
matrix:
    allow_failures:
        - rust: nightly
    fast_finish: true
install:
    ./.travis/ncurses-install
script:
    - cargo build -vv
    - cargo build -vv --features docs-rs
    - cargo run --example ncursesw-version
