[package]
name = "ncursesw"
version = "0.4.0"
authors = ["Steve Whittle <narfit66@googlemail.com>"]
description = "A fat wrapper around the ncurses TUI library"
repository = "https://github.com/narfit66/ncursesw-rs"
documentation = "https://narfit66.github.io/ncursesw-rs/ncursesw/index.html"
readme = "README.md"
keywords = ["ncurses", "TUI"]
license = "MIT"
build = "build.rs"

[dependencies]
libc = "0.2"
errno = "*"
custom_error = "1.7"
ascii = "0.9"
semver = "0.9"
lazy_static = "1.4"

[build-dependencies]
pkg-config = "0.3"
bindgen = "0.52"

[features]
# conditional compulation of KEY_RESIZE to return as a NCurseswError::KeyResize (the default) for getch(), mvgetch(),
# mvwgetch(), wgetch(), get_wch(), mvget_wch(), mvwget_wch() and wget_ch().
key_resize_as_error = []
# conditional compulation of KEY_EVENT to return as a NCurseswError::KeyEvent (the default) for getch(), mvgetch(),
# mvwgetch(), wgetch(), get_wch(), mvget_wch(), mvwget_wch() and wget_ch().
key_event_as_error = []

[lib]
name = "ncursesw"
