[package]
name = "ncursesw"
version = "0.1.1"
authors = ["Steve Whittle <narfit66@googlemail.com>"]
description = "A fat wrapper around the ncurses TUI library"
documentation = "https://github.com/narfit66/ncursesw-rs"
homepage = "https://github.com/narfit66/ncursesw-rs"
repository = "https://github.com/narfit66/ncursesw-rs"
readme = "README.md"
keywords = ["ncurses", "TUI"]
license = "MIT"
build = "build.rs"

[dependencies]
libc = "0.2"
custom_error = "1.6.0"
ascii = "0.9.1"
semver = "0.9.0"

[build-dependencies]
bindgen = "0.44.0"

[lib]
name = "ncursesw"
