[package]
name = "ncursesw"
version = "0.3.2"
authors = ["Steve Whittle <narfit66@googlemail.com>"]
description = "A fat wrapper around the ncurses TUI library"
repository = "https://github.com/narfit66/ncursesw-rs"
documentation = "https://narfit66.github.io/ncursesw-rs/ncursesw/index.html"
readme = "README.md"
keywords = ["ncurses", "TUI"]
license = "MIT"
build = "build.rs"

[dependencies]
libc = "0.2"
custom_error = "1.6.0"
ascii = "0.9.1"
semver = "0.9.0"
lazy_static = "1.3.0"

[build-dependencies]
bindgen = "0.44.0"

[features]
# conditional compulation of KEY_RESIZE to return as a NCurseswError::KeyResize for getch(), mvgetch(),
# mvwgetch(), wgetch(), get_wch(), mvget_wch(), mvwget_wch() and wget_ch().
key_resize_as_error = []
# conditional compulation of KEY_EVENT to return as a NCurseswError::KeyEvent for getch(), mvgetch(),
# mvwgetch(), wgetch(), get_wch(), mvget_wch(), mvwget_wch() and wget_ch().
key_event_as_error = []

[lib]
name = "ncursesw"
